name: Run Code Analysis

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
     - 'main'
    paths-ignore:
     - 'README.md'
     - '.github/workflows/**'

jobs:
  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          repository: KrishnaJallipalliQ/dummy-C- 
          fetch-depth: 0
          
      - uses: KrishnaJallipalliQ/ACTION-QA-Apex-PMD@main
        with:
          code-analysis-directory: "${{ secrets.SOURCE_PATH }}" 
          rulesets-path: "${{ secrets.PATH_RULES }}"
          code-analysis-token: "${{ secrets.PMD_APEX_TOKEN }}"
         

