name: SonarQube Analysis with PMD

on:
  push:
    branches:
      - main

jobs:
  sonarqube_pmd_analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: PMD Analysis
      uses: legetz/setup-pmd@7.0.0-rc3
    - name: Run PMD
      run: |
        # Run PMD analysis and generate the report
        pmd-bin-7.0.0-rc3/bin/run.sh pmd -d src/classes -R ruleset.xml -f xml -r pmd-report.xml
        
    - name: Upload PMD Report
      uses: actions/upload-artifact@v2
      with:
        name: pmd-report
        path: pmd-report.xml 

