name: Analysis PMD

on:
  push:
    branches:
      - test

jobs:
  sonarqube_pmd_analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: PMD Analysis
      uses: legetz/setup-pmd@7.0.0-rc3
    - name: Debug
      run: |
        ls 
        echo "Current working directory: $(pwd)"
    - name: Run PMD
      run: pmd check --dir ./apex-recipes-main/force-app/main/default/classes/ATK.cls

