name: OWASP

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Zap scan for web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: test
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          cmd_options: "docker run -v $(pwd):/zap/wrk/:rw --user root owasp/zap2docker-stable zap-full-scan.py -t http://testphp.vulnweb.com/ -r report.html"
          http_login_form: 'login.php'
          http_login_http_username: 'test'
          http_login_http_password: 'test'
