name: OWASP

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Zap scan for web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://testphp.vulnweb.com/'
          cmd_options: '-x "${{ github.workspace }}/zap_report.xml"'
          http_login_form: 'login.php'
          http_login_http_username: 'test'
          http_login_http_password: 'test'
